version: '3'
services:
  web:
    build: .
    command: bash -c "bundle exec rails db:migrate && bundle exec rails server -b 0.0.0.0 -p 3005"
    volumes:
      - ".:/app"
    ports:
      - "3005:3005"
volumes:
  .:
    external: true