---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/login":
    post:
      summary: login user
      tags:
      - User Sessions
      parameters: []
      responses:
        '200':
          description: successful
        '401':
          description: failed
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                user:
                  type: object
                  properties:
                    email:
                      type: string
                    password:
                      type: string
                  required:
                  - email
                  - password
              required:
              - user
  "/logout":
    delete:
      summary: logout user
      tags:
      - User Sessions
      parameters:
      - name: Authorization
        in: header
        required: true
        description: JWT token
        schema:
          type: string
      responses:
        '204':
          description: successful
        '401':
          description: failed
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: localhost:3004/
